### ISSUE TITLE
create descriptor wallet give unexpected results

### ISSUE THREAD

**Issue by kaspar-nl** [LNP-BP/descriptor-wallet#26] opened 2022-01-20 21:19 UTC
btc-cold is the bin file to carry out all kinds of functions including creating a wallet. The basic idea is that you need to input the following arguments to create a wallet: btc-cold **<DESCRIPTOR> <OUTPUT_FILE>**.

The **<OUTPUT_FILE>** is clear, it is the file that will be creator to store the data. 
I would expect that the  **<DESCRIPTOR>** would be the Miniscript command to define the wallet e.g. wsh(tpubDCj3FLoMDHpcfex7esm3hRw5xie6jDzrKpdJ4mLD95wZLdUHXoiw9tJAamG7gaTJb4yiLyGAAKwQah8c2yAoyR5UXtyY6xW3n8vNoWZMmdM/0/*) or other Miniscript Descriptors (e.g. see https://bitcoindevkit.org/descriptors/). 

I tried many different DESCRIPTORS, but I can't get it to work. It would be very helpful if some samples are provided that work, to better understand what DESCRIPTORS are valid and not. (Probably the soure code could reveal some clues....). 

As an examples what will NOT work:
`btc-cold create "wpkh(tpubEBr4i6yk5nf5DAaJpsi9N2pPYBeJ7fZ5Z9rmN4977iYLCGco1VyjB9tvvuvYtfZzjD5A8igzgw3HeWeeKFmanHYqksqZXYXGsw5zjnj7KM9/*)" outputfile`
--> output is `«Error in BASE58 key encoding»`

I also tried `tpriv` addresses, and Descriptors such as `[d34db33f/44'/0'/0']xpub6ERApfZwUNrhL.......rBGRjaDMzQLcgJvLJuZZvRcEL/0/*`

It is probably NOT A BUG, but just unclear to me (not familiar from with RUST, but usually working with e.g. Python/JS/PHP/HTML/SQL.

**Comment by dr-orlovsky** [comment] 2022-01-21 07:45
You are right, it expects (at least should expect) the descriptor and miniscript. I am using it myself for production purposes and it does work with me for that purpose. What you should keep in mind here:

- it does not accepts any form of private keys in the descriptor to discourage this practice. Descriptor wallet clearly distinguish read-only wallet (`btc-cold`) and hot wallet (`btc-hot`). Use the later to work with the private keys

- as a consequence, you can't provide `btc-cold` with arbitrary hardened derivation path, since this will require knowledge of the private key. Instead, you need to use syntax like `m=[fingerprint_or_xpubid]/X'/Y'=[xpub/zpub...]/N/M`. 

Finally, it requries slightly modified version of derivation path, which _must_ start with `m` part, indicating that the derivation happens from an extended master key, which may be followed by `=[..]`, where you put that extended *public* master key, its fingerprint or id into the square brackets. Otherwise, if the extended master key is not known, you have to start your derivation with `/` before the first derivation component.

That is the reason you can't create descriptors that you have referenced.

We plan to make these into a BIP proposal to enable full separation of hot and cold wallets a good practice.

**Comment by dr-orlovsky** [comment] 2022-01-21 07:47
Just try 

```
btc-cold create "wpkh(m=[tpubEBr4i6yk5nf5DAaJpsi9N2pPYBeJ7fZ5Z9rmN4977iYLCGco1VyjB9tvvuvYtfZzjD5A8igzgw3HeWeeKFmanHYqksqZXYXGsw5zjnj7KM9]/*)" outputfile
```

and everything should work. You MUST provide the origin for the xpub and layout it as a part of derivation path, not just simple extended key.

**Comment by kaspar-nl** [comment] 2022-01-21 21:23
-1-
Thanks for the two examples, and yes I can use these as an input for the `descriptor` (with `btc-cold create` ), but when I -after creating the wallet- use `btc-cold address outputfile` I will get `Error: DescriptorDerivePattern`. I checked the source code, and it looks like `descriptor.derive_pattern_len` = 1, but must be 2.  Do you also get this message when you have entered the 2nd example code? If not, what is going wrong with my example?

-2-
When using the `btc-cold construct` command. I got the error ` invalid key derivation in input descriptor`. Not sure which imput would work. Please share a working example, so we could also build/try this. 

It would really be helpful to show more working examples, and I am thinking about writing a step-by-step tutorial to show how to test and use the descriptor wallet. 

Thanks in advance for your help!

**Comment by dr-orlovsky** [comment] 2022-03-20 11:57
Closing assuming the issue is solved. If not, pls re-open it providing more context.

**Closed by dr-orlovsky** 2022-03-20 11:57 UTC
Labels: question
